[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
# Always pull latest image on rebuild
watchPatterns = ["**"]

[deploy]
healthcheckPath = "/alive"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Auto-deploy settings
[deploy.triggers]
# Automatically deploy on git push
gitPush = true
