[build]
builder = "dockerfile"
dockerfilePath = "monitor/Dockerfile"
watchPatterns = ["monitor/**"]

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
