[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.oauth2"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Auto-deploy settings
[deploy.triggers]
gitPush = true
